// <auto-generated />
using System;
using COMTUR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace COMTUR.Migrations
{
    [DbContext(typeof(ComturDBContext))]
    [Migration("20240527131650_teste")]
    partial class teste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("COMTUR.Models.AtracaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("atracaoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("IdTipoAtracao")
                        .HasColumnType("integer")
                        .HasColumnName("idtipoatracao");

                    b.Property<int>("IdTurismo")
                        .HasColumnType("integer")
                        .HasColumnName("idturismo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qrcode");

                    b.Property<int?>("TipoAtracaoModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoAtracao");

                    b.HasIndex("IdTurismo");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("TipoAtracaoModelId");

                    b.ToTable("atracao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Show da Ana Castela",
                            IdTipoAtracao = 1,
                            IdTurismo = 1,
                            IdUsuario = 4,
                            Nome = "Ana Castela",
                            QRCode = "123456"
                        });
                });

            modelBuilder.Entity("COMTUR.Models.AuditoriaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NomeEntidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NovosValores")
                        .HasColumnType("text");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValoresAntigos")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("COMTUR.Models.EmpresaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("empresaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endereco");

                    b.Property<int>("IdTipoTurismo")
                        .HasColumnType("integer")
                        .HasColumnName("tipoturismoid");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<int?>("TipoTurismoModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoTurismo");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("TipoTurismoModelId");

                    b.ToTable("empresa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CNPJ = "12.345.678/9012-34",
                            Descricao = "Em AnaStore, acreditamos que cada pessoa tem sua própria história para contar, e é por isso que oferecemos uma seleção cuidadosamente analisada de roupas e acessórios que abraçam uma variedade de estilos, desde o casual chic até o elegante e sofisticado. Nossas coleções são atualizadas regularmente para garantir que nossos clientes sempre encontrem algo novo e empolgante a cada visita.",
                            Endereco = "Rua Ana Carolina, 0902 - Jardim Aana, Jales - SP, 15700-123",
                            IdTipoTurismo = 2,
                            IdUsuario = 5,
                            Nome = "AnaStore"
                        },
                        new
                        {
                            Id = 2,
                            CNPJ = " 30.475.124/0001-94 ",
                            Descricao = "A Tropicale oferece uma experiência única ao priorizar a qualidade em todas as etapas, desde a seleção dos ingredientes até o armazenamento dos sorvetes. Equipada com tecnologia de ponta, proporciona um ambiente acolhedor para famílias e amigos desfrutarem momentos especiais juntos. O cardápio diversificado inclui sorvetes de massa, picolés de fruta e ao leite, picolés gourmet e opções sem lactose.",
                            Endereco = "Rua Prof. Rubião Meira, 4120 - Jardim Paulista, Jales - SP, 15700-426",
                            IdTipoTurismo = 3,
                            IdUsuario = 6,
                            Nome = "Tropicale Brasil Sorvetes"
                        });
                });

            modelBuilder.Entity("COMTUR.Models.ImagemAtracaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("imagematracaoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAtracao")
                        .HasColumnType("integer")
                        .HasColumnName("idatracao");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imagem");

                    b.Property<string>("LegendaImagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legendaimagem");

                    b.HasKey("Id");

                    b.HasIndex("IdAtracao");

                    b.ToTable("imagematracao");
                });

            modelBuilder.Entity("COMTUR.Models.ImagemEmpresaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("imagemempresaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("idempresa");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imagem");

                    b.Property<string>("LegendaImagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legendaimagem");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("imagemempresa");
                });

            modelBuilder.Entity("COMTUR.Models.ImagemNoticiaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("imagemnoticiaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdNoticia")
                        .HasColumnType("integer")
                        .HasColumnName("idnoticia");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imagem");

                    b.Property<string>("LegendaImagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legendaimagem");

                    b.HasKey("Id");

                    b.HasIndex("IdNoticia");

                    b.ToTable("imagemnoticia");
                });

            modelBuilder.Entity("COMTUR.Models.ImagemTurismoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("imagemturismoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdTurismo")
                        .HasColumnType("integer")
                        .HasColumnName("idturismo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imagem");

                    b.Property<string>("LegendaImagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legendaimagem");

                    b.HasKey("Id");

                    b.HasIndex("IdTurismo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("imagemturismo");
                });

            modelBuilder.Entity("COMTUR.Models.NoticiaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("noticiaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateOnly>("DataPublicacao")
                        .HasColumnType("date")
                        .HasColumnName("datapublicacao");

                    b.Property<string>("HoraPublicacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("horapublicacao");

                    b.Property<int?>("IdTurismo")
                        .HasColumnType("integer")
                        .HasColumnName("idturismo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.Property<string>("Subtitulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subtitulo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("IdTurismo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("noticia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Conteudo = "Hoje, a cidade de Jales testemunhou um marco na cena da moda local com a grandiosa inauguração da AnaStore, a mais recente empreitada da renomada empresária Ana Carolina. Situada no coração da área comercial, a loja promete revolucionar o estilo dos moradores locais com suas coleções exclusivas e uma abordagem única para moda e estilo.\r\n\r\nCom uma cerimônia de inauguração repleta de glamour e entusiasmo, a Sra. Ana Carolina expressou sua gratidão pela calorosa recepção que a comunidade de Jales ofereceu à sua mais recente iniciativa empresarial. \"A AnaStore não é apenas uma loja de roupas, é um espaço onde a moda encontra a expressão pessoal. Queremos ser mais do que apenas uma opção de compras, queremos ser uma fonte de inspiração para todos aqueles que desejam expressar sua individualidade através do estilo\", afirmou a visionária empresária.\r\n\r\nOs clientes que compareceram ao evento de inauguração foram recebidos com um desfile de moda exclusivo, apresentando as últimas tendências e peças selecionadas cuidadosamente pela equipe da AnaStore. De vestuário casual a trajes de gala, a loja oferece uma ampla variedade de opções para atender a todos os gostos e ocasiões.\r\n\r\nAlém de oferecer uma experiência de compra excepcional, a AnaStore também se compromete com a sustentabilidade ambiental e social. \"Estamos empenhados em promover práticas comerciais éticas e sustentáveis, desde a escolha dos materiais até as condições de trabalho em nossas fábricas parceiras. Queremos que nossos clientes se sintam bem não apenas com suas escolhas de moda, mas também com o impacto positivo que estão causando no mundo\", ressaltou Ana Carolina.\r\n\r\nA AnaStore já se destaca como um destino imperdível para os amantes da moda em Jales, e sua inauguração promete ser apenas o começo de uma jornada emocionante rumo ao sucesso e à inovação na indústria da moda local. ",
                            DataPublicacao = new DateOnly(2024, 5, 15),
                            HoraPublicacao = "10:30",
                            IdUsuario = 2,
                            Subtitulo = "A cidade de Jales recebeu hoje um novo marco na indústria da moda com a inauguração triunfante da AnaStore, uma loja que promete revolucionar o cenário fashion local.",
                            Titulo = "Grande Inauguração da AnaStore: Uma Celebração de Estilo e Elegância!"
                        },
                        new
                        {
                            Id = 2,
                            Conteudo = "Os aficionados por sorvete têm motivos para comemorar com o mais recente lançamento da Tropicale, uma das principais marcas de sorvetes do país. Hoje, a empresa revelou seu mais novo sabor de dar água na boca: \"Laravi\", uma deliciosa combinação de frescor e doçura inspirada na laranja.\r\n\r\nCom a chegada do verão, a Tropicale decidiu elevar a experiência dos consumidores com uma criação que captura o sabor vibrante e refrescante da fruta cítrica favorita de muitos. O sabor \"Laravi\" promete oferecer uma explosão de sabor a cada colherada, combinando o suculento aroma da laranja com a suavidade e cremosidade característica dos sorvetes da marca.\r\n\r\nEm uma entrevista exclusiva, o diretor de desenvolvimento de produtos da Tropicale, Carlos Mendes, compartilhou insights sobre a inspiração por trás do novo sabor. \"Queríamos criar algo verdadeiramente único que despertasse a nostalgia do verão e proporcionasse uma experiência memorável aos nossos clientes. O 'Laravi' é uma homenagem à simplicidade e à autenticidade da laranja, e estamos confiantes de que será um sucesso entre os amantes de sorvete de todas as idades\", afirmou Mendes.\r\n\r\nAlém de seu irresistível sabor, o \"Laravi\" também se destaca por sua composição de alta qualidade, feita com ingredientes naturais e frescos. A Tropicale reiterou seu compromisso com a excelência e a inovação, garantindo que cada porção de sorvete seja uma experiência verdadeiramente indulgente e satisfatória.\r\n\r\nO lançamento do sabor \"Laravi\" já está gerando grande expectativa entre os consumidores, que mal podem esperar para experimentar essa nova criação da Tropicale. Com sua promessa de refrescar os dias quentes de verão com uma explosão de sabor, o \"Laravi\" está pronto para se tornar o novo favorito entre os apreciadores de sorvete em todo o país.",
                            DataPublicacao = new DateOnly(2024, 5, 27),
                            HoraPublicacao = "08:30",
                            IdUsuario = 2,
                            Subtitulo = "Combinando a refrescância da laranja com a suavidade do sorvete, \"Laravi\" promete ser uma verdadeira explosão cítrica de sabor que cativará os paladares de todos.",
                            Titulo = "Tropicale Lança Novo Sabor chamado Laravi: Uma Explosão Cítrica de Sabor!"
                        });
                });

            modelBuilder.Entity("COMTUR.Models.SessaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idssessao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emailusuario");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    b.Property<string>("NivelAcesso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivelacesso");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomeusuario");

                    b.Property<bool>("StatusSessao")
                        .HasColumnType("boolean")
                        .HasColumnName("statussessao");

                    b.Property<string>("TokenSessao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tokensessao");

                    b.Property<int?>("UsuarioModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioModelId");

                    b.ToTable("sessao");
                });

            modelBuilder.Entity("COMTUR.Models.TipoAtracaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipoatracaoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("tipoatracao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Show"
                        });
                });

            modelBuilder.Entity("COMTUR.Models.TipoTurismoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tipoturismoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.Property<string>("Imagem")
                        .HasColumnType("text")
                        .HasColumnName("imagemtipoturismo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("tipoturismo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdUsuario = 4,
                            Nome = "Expo"
                        },
                        new
                        {
                            Id = 2,
                            IdUsuario = 4,
                            Nome = "Varejo"
                        },
                        new
                        {
                            Id = 3,
                            IdUsuario = 4,
                            Nome = "Alimento"
                        });
                });

            modelBuilder.Entity("COMTUR.Models.TurismoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("turismoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("DiaFuncionamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diafuncionamento");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("horario");

                    b.Property<int>("IdTipoTurismo")
                        .HasColumnType("integer")
                        .HasColumnName("idtipoturismo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("local");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qrcode");

                    b.Property<int?>("TipoTurismoModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoTurismo");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("TipoTurismoModelId");

                    b.ToTable("turismo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Praça da Fonte",
                            DiaFuncionamento = "Todos os dias",
                            Horario = "18:00",
                            IdTipoTurismo = 1,
                            IdUsuario = 2,
                            Local = "Praça da Fonte",
                            Nome = "Praça da Fonte",
                            QRCode = "123456"
                        });
                });

            modelBuilder.Entity("COMTUR.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emailusuario");

                    b.Property<string>("ImagemPerfilUsuario")
                        .HasColumnType("text")
                        .HasColumnName("imagemperfilusuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senhausuario");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("tipousuario");

                    b.HasKey("Id");

                    b.ToTable("usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailUsuario = "usuario@gmail.com",
                            Nome = "Usuário",
                            SenhaUsuario = "123456",
                            Telefone = "(11) 11111-1111",
                            TipoUsuario = 1
                        },
                        new
                        {
                            Id = 2,
                            EmailUsuario = "funcionario@gmail.com",
                            Nome = "Funcionário",
                            SenhaUsuario = "123456",
                            Telefone = "(22) 22222-2222",
                            TipoUsuario = 2
                        },
                        new
                        {
                            Id = 3,
                            EmailUsuario = "empresario@gmail.com",
                            Nome = "Empresário",
                            SenhaUsuario = "123456",
                            Telefone = "(33) 33333-3333",
                            TipoUsuario = 3
                        },
                        new
                        {
                            Id = 4,
                            EmailUsuario = "administrador@gmail.com",
                            Nome = "Administrador",
                            SenhaUsuario = "123456",
                            Telefone = "(44) 44444-4444",
                            TipoUsuario = 4
                        },
                        new
                        {
                            Id = 5,
                            EmailUsuario = "ana@gmail.com",
                            Nome = "Ana",
                            SenhaUsuario = "123456",
                            Telefone = "(55) 5555-5555",
                            TipoUsuario = 3
                        },
                        new
                        {
                            Id = 6,
                            EmailUsuario = "atendimento@lojatropicale.com.br",
                            Nome = "Tropicale",
                            SenhaUsuario = "123456",
                            Telefone = "(17) 3632-0117",
                            TipoUsuario = 3
                        });
                });

            modelBuilder.Entity("COMTUR.Models.AtracaoModel", b =>
                {
                    b.HasOne("COMTUR.Models.TipoAtracaoModel", "TipoAtracaoModel")
                        .WithMany()
                        .HasForeignKey("IdTipoAtracao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COMTUR.Models.TurismoModel", "TurismoModel")
                        .WithMany("Atracao")
                        .HasForeignKey("IdTurismo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COMTUR.Models.UsuarioModel", "UsuarioModel")
                        .WithMany("Atracao")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COMTUR.Models.TipoAtracaoModel", null)
                        .WithMany("Atracao")
                        .HasForeignKey("TipoAtracaoModelId");

                    b.Navigation("TipoAtracaoModel");

                    b.Navigation("TurismoModel");

                    b.Navigation("UsuarioModel");
                });

            modelBuilder.Entity("COMTUR.Models.EmpresaModel", b =>
                {
                    b.HasOne("COMTUR.Models.TipoTurismoModel", "TipoTurismoModel")
                        .WithMany()
                        .HasForeignKey("IdTipoTurismo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COMTUR.Models.UsuarioModel", "UsuarioModel")
                        .WithMany("Empresas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COMTUR.Models.TipoTurismoModel", null)
                        .WithMany("Empresa")
                        .HasForeignKey("TipoTurismoModelId");

                    b.Navigation("TipoTurismoModel");

                    b.Navigation("UsuarioModel");
                });

            modelBuilder.Entity("COMTUR.Models.ImagemAtracaoModel", b =>
                {
                    b.HasOne("COMTUR.Models.AtracaoModel", "AtracaoModel")
                        .WithMany("ImagemAtracao")
                        .HasForeignKey("IdAtracao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtracaoModel");
                });

            modelBuilder.Entity("COMTUR.Models.ImagemEmpresaModel", b =>
                {
                    b.HasOne("COMTUR.Models.EmpresaModel", "EmpresaModel")
                        .WithMany("ImagemEmpresa")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpresaModel");
                });

            modelBuilder.Entity("COMTUR.Models.ImagemNoticiaModel", b =>
                {
                    b.HasOne("COMTUR.Models.NoticiaModel", "NoticiaModel")
                        .WithMany("ImagemNoticia")
                        .HasForeignKey("IdNoticia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoticiaModel");
                });

            modelBuilder.Entity("COMTUR.Models.ImagemTurismoModel", b =>
                {
                    b.HasOne("COMTUR.Models.TurismoModel", "TurismoModel")
                        .WithMany("ImagemTurismo")
                        .HasForeignKey("IdTurismo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COMTUR.Models.UsuarioModel", "UsuarioModel")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TurismoModel");

                    b.Navigation("UsuarioModel");
                });

            modelBuilder.Entity("COMTUR.Models.NoticiaModel", b =>
                {
                    b.HasOne("COMTUR.Models.TurismoModel", "TurismoModel")
                        .WithMany("Noticia")
                        .HasForeignKey("IdTurismo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("COMTUR.Models.UsuarioModel", "UsuarioModel")
                        .WithMany("Noticia")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TurismoModel");

                    b.Navigation("UsuarioModel");
                });

            modelBuilder.Entity("COMTUR.Models.SessaoModel", b =>
                {
                    b.HasOne("COMTUR.Models.UsuarioModel", "UsuarioModel")
                        .WithMany()
                        .HasForeignKey("UsuarioModelId");

                    b.Navigation("UsuarioModel");
                });

            modelBuilder.Entity("COMTUR.Models.TipoTurismoModel", b =>
                {
                    b.HasOne("COMTUR.Models.UsuarioModel", "UsuarioModel")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioModel");
                });

            modelBuilder.Entity("COMTUR.Models.TurismoModel", b =>
                {
                    b.HasOne("COMTUR.Models.TipoTurismoModel", "TipoTurismoModel")
                        .WithMany()
                        .HasForeignKey("IdTipoTurismo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COMTUR.Models.UsuarioModel", "UsuarioModel")
                        .WithMany("Turismos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COMTUR.Models.TipoTurismoModel", null)
                        .WithMany("Turismo")
                        .HasForeignKey("TipoTurismoModelId");

                    b.Navigation("TipoTurismoModel");

                    b.Navigation("UsuarioModel");
                });

            modelBuilder.Entity("COMTUR.Models.AtracaoModel", b =>
                {
                    b.Navigation("ImagemAtracao");
                });

            modelBuilder.Entity("COMTUR.Models.EmpresaModel", b =>
                {
                    b.Navigation("ImagemEmpresa");
                });

            modelBuilder.Entity("COMTUR.Models.NoticiaModel", b =>
                {
                    b.Navigation("ImagemNoticia");
                });

            modelBuilder.Entity("COMTUR.Models.TipoAtracaoModel", b =>
                {
                    b.Navigation("Atracao");
                });

            modelBuilder.Entity("COMTUR.Models.TipoTurismoModel", b =>
                {
                    b.Navigation("Empresa");

                    b.Navigation("Turismo");
                });

            modelBuilder.Entity("COMTUR.Models.TurismoModel", b =>
                {
                    b.Navigation("Atracao");

                    b.Navigation("ImagemTurismo");

                    b.Navigation("Noticia");
                });

            modelBuilder.Entity("COMTUR.Models.UsuarioModel", b =>
                {
                    b.Navigation("Atracao");

                    b.Navigation("Empresas");

                    b.Navigation("Noticia");

                    b.Navigation("Turismos");
                });
#pragma warning restore 612, 618
        }
    }
}
